---
title: Activar proceso
---
flowchart TD
    H[/Proceso a activar/]
    H --> I{"¿Partición \ndel proceso \n está en MV?"}
    I -- No --> Z
    M -- No --> N["Swap out de una \n partición víctima\n (del mismo tamaño \n que la del proceso)"] --> P
    I -- Sí --> M{"¿Hay una \n partición libre y \n suficiente en MP?"}
    M -- Sí --> P[Swap in a \nesa partición] --> Z
    Z((Fin))
