---
title: Admitir proceso nuevo
---
flowchart TD
    H[/Proceso a admitir/]
    H --> H2["Buscar partición asignable (best-fit)"]
    H2 --> I{"¿Hay una \n partición libre y \n suficiente en MP?"}
    I -- Sí -->Q[Admitir el proceso\n y asignarlo a \n esa partición] --> Fin
    I -- No --> S{"¿Espacio \ndisponible en MV?\n (multiprog <= 5)"}
    S -- Sí -->R[Admitir el proceso \n suspendido en MV] --> Fin
    S -- No --> N[Rechazar \nel proceso] --> Fin
    Fin((Fin))
