---
title: Simulador
---
flowchart TD
    Start[/Leer carga de trabajo\n del archivo de entrada/] --> Ord[Ordenar procesos por\n tiempo de arribo]
    Ord --> Init["t := 0\n quantum := 0"]
    Init --> CondFin{"¿Carga de\n trabajo\n terminada?"}
    CondFin -- Sí --> Fin
    CondFin -- No --> CondPNuevo{"¿Proceso\n nuevo sin \n admitir?"}
    CondPNuevo -- Sí --> AdmitirP[["Admitir proceso(s)\n nuevo(s)"]]
    CondPNuevo -- No --> CondPTerminado{"¿Proceso \n en la CPU \n terminado?"}
    AdmitirP --> CondPEjecutando{"¿CPU \nocupada?"}
    CondPEjecutando -- Sí --> Progreso[Incrementar progreso \n del proceso en ejecución]
    CondPEjecutando -- No --> FinBucle
    Progreso --> CondPTerminado
    CondPTerminado -- Sí --> TerminarP[Terminar proceso \n y liberar partición]
    CondPTerminado -- No --> CondQuantum{"¿q == 2?"}
    CondQuantum -- Sí --> ExpropiarP[Expropiar proceso \n y enviarlo al final \n de la cola de listos]
    CondQuantum -- No --> FinBucle
    ExpropiarP --> AsignarSigP[Asignar CPU al \n siguiente proceso \n de la cola de listos]
    TerminarP ---> LiberarCPU["quantum := 0"] --> AsignarSigP
    AsignarSigP --> ActivarP[["Activar proceso\n (si está ausente)"]] --> ImprimirBucle
    ImprimirBucle[/Imprimir estado de los \n procesos y la memoria/] --> FinBucle
    FinBucle["t := t + 1 \n quantum := quantum % 2 + 1"] ----> CondFin
    Fin[/Imprimir reporte/] --> Exit((Fin))
